### ISSUE TITLE
Ability to add site to blocked sites list manually

### ISSUE THREAD

**Issue by maksimkurb** [anticensority/chromium-extension#3]
Some sites are not listed in Roskomnadzor registry, but blocked by some ISPs.
For example, I can't visit [archive.org](http://archive.org) on MTS.

Also, it would be nice to add automated population of this list, based on behavior: for example, if I visit blocked site, I will be redirected to [block.mts.ru/?host=...](block.mts.ru/?host=), so extension can catch this redirection, then add previous link url to proxifying list and redirect to this blocked site again.

**Comment by ilyaigpetrov** [comment]
I will try to find time for this, but currently you may try adding archive.org to [reestr.rublacklist.net](https://reestr.rublacklist.net/messages/add).

**Comment by ilyaigpetrov** [comment]
1. Adding custom sites is possible in v0.20 if you add own proxies or use local TOR.
2. Behavior-based detection could be possible, e.g., based on response coming from IP-address of a provider. Unfortunately my provider redirect-reply has IP of the site requested (for HTTP):
```js
"http://www.kasparov.ru"
{
  frameId: 0,
  fromCache: false,
  ip: "52.4.68.142", // Belongs to www.kasparov.ru
  method: "GET",
  parentFrameId: -1,
  redirectUrl: "http://PAGE-OF-MY-PROVIDER.ru", // Too late to use proxy after catching redirect.
  requestId: "31499",
  statusCode: 302,
  statusLine: "HTTP/1.1 302 Found",
  tabId: 829,
  timeStamp: 1487265353517.948,
  type: "main_frame",
  url: "http://www.kasparov.ru/",
}
```
So I see no way to spot blocked URL before HTTP-redirect reaches browser.
3. I can't check HTTPS yet because my provider doesn't block HTTPS today, but, I believe, chances are low.

**Comment by maksimkurb** [comment]
> Too late to use proxy after catching redirect

What if catch this redirection and store it in some `cache` (just array or map) with the `tabId` ([chrome.tabs](https://developer.chrome.com/extensions/tabs))?
You can inject content script on each provider site, send message to background script, which add this site to blocked-sited-list and redirect this tab back to blocked site (background script can take [sender `tabId`](https://stackoverflow.com/questions/6202953/obtaining-this-tab-id-from-content-script-in-chrome-extension) and take originally opened site from `cache`)

**Comment by ilyaigpetrov** [comment]
@maksimkurb, yes, something like this is for sure possible, but not without a notice from a user, because:

1. You have to reload a blocked tab and user will notice the reload (or he has to reload tab himself).
2. One reload may be not enough, because tab with a html page makes many sub-requests which may be to another blocked hostnames (like private CDN on another domain).

This idea deserves experimentation and if user experience won't be too poor and implementation won't be too complex then it should be included into the extension.

Also `manifest.json` where you define content-script with `matches` can't be changed by extensions itself.

Thanks for your idea, I had something similar in mind though. I have other ideas about extension but I have few time for implementing all the ideas (you may email me and collaborate).

**Comment by ilyaigpetrov** [comment]
I was thinking about adding this feature into the next build. Automatically adding hostnames to exceptions and repeating requests has the following cons:
* What if an error occurs during submitting a payment and we automatically repeat the request through our proxies — it can happen that payment is submitted two times. Avoiding automate behavior during failed POST requests helps a little, but still leaves a chance of inappropriate GET repeats.
* If hostnames are added automatically then there is risk of overflow/overflood on the number of proxied hostsnames.
* Repeating requests won't come unnoticed by a user.

Taking these cons into account I decided not to add automatic proxying, but alleviate the process of adding hosts to exceptions to 2 clicks away from the error page.
